name = "absensi-sekolah"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "absensi-db"
database_id = "d420eccd-8565-4055-aa0e-a6e59f1203da"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "absensi-bucket"
